### ISSUE TITLE
Error on initializing CucumberPerf object

### ISSUE THREAD

**Issue by dwanedebonocatena** [mpinardi/cucumber-performance#10]
Hi, I am trying to use your library however when initializing an instance of Cucumber Perf, I am getting this error:

`cucumber.runtime.FeaturePathFeatureSupplier.<init>(Lcucumber/runtime/model/FeatureLoader;Lcucumber/runtime/RuntimeOptions;)V`

This is being triggered within the constructor of **CucumberPerf(clazz)** on the line:
`this.features = FeatureBuilder.getFeatures(ro);`

The interesting thing is, that if I debug and go inside **getFeatures()** and I evaluate the expression `new FeaturePathFeatureSupplier(featureLoader, runtimeOptions).get()` in debug mode (which is actually the return value of **getFeatures()** ) it evaluates correctly with an ArrayList containing the feature files details.

I am using io.cucumber cucumber-java 4.2.0 and cucumber-perf 1.3.1

Any clue what the issue might be?

**Comment by mpinardi** [comment]
So that error is happening inside of cucumber and I cant seem to reproduce it.
What does your class look like? What are your annotations?
Can you provide any more details?

**Comment by dwanedebonocatena** [comment]
Hi @mpinardi , 

Sorry for the delay. This is how I am trying it. Basically I created a class with a main method in which I pass in runtime options.


public class RunPerformanceTests {

    public static void main(String[] args) {
        
        PerfRuntimeOptions options = new PerfRuntimeOptions();
        options.addTagFilters(Arrays.asList("@performancetest"));       
        options.addPlanPaths(Arrays.asList(
         "src/test/resources/quality/products/core/performance/plans"));
        options.addCucumberOptions(Arrays.asList(
          new String[]{" g","classpath:com.catena.qa.framework.quality",
          "src/test/resources/quality/products/core/functionality/services/settings-ms"}));

        CucumberPerf cukePerf = new CucumberPerf(options);
        try {
            cukePerf.runThreads();
        } catch (Throwable e) {
            System.out.println("Error: " + e.getMessage());
        }
        System.out.println("Total Ran: " + cukePerf.getTotalRanCount());
        System.out.println("RunTime: " + cukePerf.getRunTime());
        System.exit(0);
    }
}

Under "src/test/resources/quality/producs/core/performance/plans" I have 1 file test.plan which contains the below:

Plan: Testing Cucumber Perf
        Simulation: simulation 1
        Group settingsCRUD.feature
        #number of threads
        Runners: 1
        #total number of threads to run.
        Count: 2
        #a optional random wait mean for before thread runs tests.
        #thread will wait between +-50% of this mean
        RandomWait: 00:00:02

**Comment by mpinardi** [comment]
you are missing a - on your glue " -g","classpath:com.catena.qa.framework.quality",
might be the issue. Don't see anything else off hand.

**Comment by dwanedebonocatena** [comment]
I must have removed it but mistake when pasting it in github. Unfortunately, that is not the cause of the issue.

**Comment by mpinardi** [comment]
Is that the full error or is it a no-such-method error?
I do see similar responses on google for when cucumber-java and cucumber-core version do not match.

**Comment by dwanedebonocatena** [comment]
Yes its a no-such-method error

```
Exception in thread "main" java.lang.NoSuchMethodError: cucumber.runtime.FeaturePathFeatureSupplier.<init>(Lcucumber/runtime/model/FeatureLoader;Lcucumber/runtime/RuntimeOptions;)V
	at cucumber.api.perf.FeatureBuilder.getFeatures(FeatureBuilder.java:33)
	at cucumber.api.perf.CucumberPerf.<init>(CucumberPerf.java:104)
	at com.catena.qa.core.framework.RunPerformanceTests.main(RunPerformanceTests.java:15)
```

This is what I have in pom file:

```
<!-- Cucumber -->
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumber.version}</version>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>${cucumber.version}</version>
        </dependency>
<!-- /Cucumber -->
<!-- Cucumber-Perf -->
        <dependency>
            <groupId>com.github.mpinardi</groupId>
            <artifactId>cucumber-perf</artifactId>
            <version>1.3.1</version>
        </dependency>
<!-- Cucumber-Perf -->
```

**Comment by mpinardi** [comment]
add:
```
<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-core</artifactId>
			<version>${cucumber.version}</version>
</dependency>
```

**Comment by dwanedebonocatena** [comment]
Hi @mpinardi , I tried to add that but it did not get a different outcome. Let me try to give you more info. on the issue:

So, from the error message that I pasted above, the issue starts from `FeatureBuilder.getFeatures(FeatureBuilder.java:33)`. 
When I set a breakpoint on this line, and evaluate the expression, I get the below:

![image](https://user-images.githubusercontent.com/38216564/59834798-e5922780-9348-11e9-8d55-f536e134d93b.png)

As you can see, I am also adding the `.get()` which would contain the return object of the <getFeatures> function. The values seem correct. Have a look maybe it helps us find the root cause. 
Thanks.

**Comment by mpinardi-bao** [comment]
Sorry i didn't see your reply awhile ago.
Unfortunately i still can't see any issues.
It is strange that it returns fine when you add the .get() to class invocation. 
I will see about making that change for the next revision of this project.
from:
FeaturePathFeatureSupplier featureSupplier = new FeaturePathFeatureSupplier(featureLoader, runtimeOptions);
		return featureSupplier.get();
to:
return new FeaturePathFeatureSupplier(featureLoader, runtimeOptions).get();
