### ISSUE TITLE
@CucumberPerfOptions annotation - plugin support

### ISSUE THREAD

**Issue by ghost** [mpinardi/cucumber-performance#5]
Hi there. I'm interested in adopting your cucumber performance test library for a project.
On the surface it looks very impressive, however I am having problems setting the plugins you've mentioned in the Wiki. More specifically, I'm looking to render a better set of reports, rather than the default summary.

Your wiki mentions plugins such as "summary_text:file://C:/test/summary", for example, however I cannot see where that will be used, when using the `@CucumberPerfOptions` annotation.
I have checked through your codebase and cannot see any reference to the 'plugin' property of the `@CucumberPerfOptions` annotation.
The `PerfRuntimeOptionsFactory` class does not appear to use it - should it?

Tested on version **1.3.0**.

**Comment by mpinardi-bao** [comment]
So this seems to be that I never hooked it up and didn't notice. Its a simple fix. 
I will try to update this week.

**Comment by mpinardi** [comment]
Fixed
