### ISSUE TITLE
Query about the metrics

### ISSUE THREAD

**Issue by ghost** [mpinardi/cucumber-performance#6]
I have a very simple feature with 1 scenario with 4 steps, each of which performs a trivial task (variable assignment, addition, etc.).

I have a working plan which executes the feature over 5 seconds, with 10 threads.

One execution produced the following results:

Feature: test.feature Count: 194 Avg: 155 Min: 13 Max: 1095
	Scenario: Test addition Count: 194 Avg: 0 Min: 0 Max: 24
		Step: x is 1 Count: 194 Avg: 0 Min: 0 Max: 2
		Step: y is 2 Count: 194 Avg: 0 Min: 0 Max: 0
		Step: I add x + y Count: 194 Avg: 0 Min: 0 Max: 13
		Step: I get the value 3 Count: 194 Avg: 0 Min: 0 Max: 7
 
I wanted to query how the metrics are calculated, for example:

- the max value of 1095ms for the feature appears to be significantly higher than the max run for the single scenario (24ms) - why is that? I'd expect the metric to reference the time taken within the step implementations.
- the max value for the scenario (24ms) is not equal to the combined max values for the steps (2 + 0 + 13 + 7 = 22ms). I appreciate 2ms is relatively trivial in this context, however it raises concerns over the integrity of the results.

Perhaps the 13ms for an integer addition can be put down to Java threads competing for the same CPU thread (?), but is this the time it took to _only_ execute the step method, or does it also include time taken to execute internal Cucumber code?

**Comment by mpinardi-bao** [comment]
So cucumber itself doesn't log runtime for a feature or even message when a feature has been run. From its perspective its just running test-cases(scenarios). So to track feature times this application uses test-run events which is a complete execution of cucumber.
