### ISSUE TITLE
Need more complete Wiki information

### ISSUE THREAD

**Issue by dmreda** [mpinardi/cucumber-performance#8]
(Sorry about the formatting, not sure how to get stuff with < and > around it to render properly....)

Hi, I need some more beginner-level information in the Wiki to get my stuff running.

I'm using Intellij IDEA and am trying to get create a Java class to run my existing Cucumber feature files.

1) What extension, if any, do I need on the Plan file? A ".txt" doesn't seem to be working.

2) I've got lots of dependencies in my Maven POM, including 
 <dependency>
            <groupId>com.github.mpinardi</groupId>
            <artifactId>cucumber-perf</artifactId>
            <version>1.3.0</version>
        </dependency>
<dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${io.cucumber.version}</version>  
        </dependency>

My main class is

import cucumber.api.junit.Cucumber;
import cucumber.api.perf.CucumberPerf;
import cucumber.api.perf.PerfRuntimeOptions;
import org.junit.runner.RunWith;
import java.util.Arrays;

@RunWith(Cucumber.class)

public class CucumberPerfTest {
    public static void main(String[] args) throws Throwable
    {
        PerfRuntimeOptions options = new PerfRuntimeOptions();
        options.addTagFilters(Arrays.asList(new String[]{"@DennisPerfTest"}));
        options.addPlanPaths(Arrays.asList(new String[]{"src/test/resources/features"}));
        options.addCucumberOptions(Arrays.asList(new String[]{"features = {CUCUMBER_FEATURES},  " + "" +
                "plugin = { CUCUMBER_FORMAT_TYPE, CUCUMBER_FORMAT_TEST_RESULTS_PATH, " +
                            "CUCUMBER_JSON_PATH, CUCUMBER_JUNIT_PATH, CUCUMBER_REPORT_PATH}, " +
                "monochrome = CUCUMBER_MONACHROME, dryRun = CUCUMBER_DRY_RUN)"}));
        CucumberPerf cukePerf = new CucumberPerf(options);

        cukePerf.runThreads();

    }

}

My plan is
@DennisPerfTest

Plan: plan
Simulation: simulation 1
Group browse_places_filter.feature
	#slices
	#these values will replace property "value out"
	|value out|
	|changed value 1|
	|changed value 2|
	#number of threads
	Runners: 2
	#total number of threads to run.
	Count: 2
#a optional random wait mean for before thread runs tests.
#thread will wait between +-50% of this mean
RandomWait: 00:00:02

#Will run all groups for the period below
Simulation Period: simulation 2 period
Group us_persons_banner.feature
	|value out|
	|changed value |
		Threads: 5
		#count is ignored in a simulation period
		Count: 1
#run time
Time: 00:00:30
RampUp: 00:00:10
RampDown: 00:00:10

but I get 

exception in thread "main" java.lang.NoClassDefFoundError: cucumber/runtime/io/URLOutputStream
	at cucumber.api.perf.PerfRuntimeOptions.<init>(PerfRuntimeOptions.java:70)
	at cucumber.api.perf.PerfRuntimeOptions.<init>(PerfRuntimeOptions.java:60)
	at gov.ic.aspace.autotest.stepdefs.CucumberPerfTest.main(CucumberPerfTest.java:23)
Caused by: java.lang.ClassNotFoundException: cucumber.runtime.io.URLOutputStream
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

Process finished with exit code 1

Any help is appreciated. Thanks!

Dennis

**Comment by dmreda** [comment]
FYI, some of my problems seem to be related to cucumber-jvm, specifically where the method URLOutputStream is located.

It was in cucumber-jvm up to version 4.2.0 of that, but then somebody moved it to the "formatters" package ( see https://github.com/dtarunnayudu/cucumber-jvm/commit/eb1a90bd5488421b06acfab4d2b32bf851cdf1db  )

**Comment by mpinardi-bao** [comment]
Plan files are just like feature files in cucumber. So it should be saved as "filename.plan".
Also thanks for finding that issue. Seems they made a breaking change and didn't move to version 5.0.
I will have a bug fix version soon and next revision will support the latest version of cucumber.

**Comment by mpinardi** [comment]
I have done many updates to the wiki. Closing.
