### ISSUE TITLE
Report metrics only for certain steps

### ISSUE THREAD

**Issue by hemathangavel** [mpinardi/cucumber-performance#9]
Is there any way we can report metrics for specific steps rather than all steps? Say if I have 5 steps, I'm more interested in the metrics reported for Step 3 and Step 5 rather than all. I'm curious if it can be controlled in a robust manner. Sometimes I want to see the metric for Step 3 & 5 and other times only Step 4. Please let me know.

**Comment by mpinardi-bao** [comment]
Currently no. I am not sure if I would ever add that functionality. I will keep it in mind.
